# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

.github/workflows/dev.ymlname: Release

on:
  push:
    paths:
      - 'packages/**'
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Get Yarn cache path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history
          # so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Use Node.js 16.x
        uses: actions/setup-node@master
        with:
          node-version: 16

      - name: Load Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Lint
        # Why do we add the "--no-error-on-unmatched-pattern" flag on this command?
        # The reason is that eslint may not locate the built files in  Windows CI environment
        # We therefore silently fail the command in this scenario.
        run: yarn lint --no-error-on-unmatched-pattern

      - name: Test
        run: NODE_ENV=staging yarn jest --verbose --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build

      # TODO: Uncomment when ready to start testing RCs

      - name: Setup CI Git User
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Configure npm
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
          cat .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          publish: yarn changeset publish
          title: 'chore(release): version packages and publish'
          commit: 'chore(release): version packages'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release to dev tag
        if: steps.changesets.outputs.published != 'true'
        run: |
          yarn changeset version --snapshot dev
          yarn changeset publish --tag dev
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
